### ISSUE TITLE
How do you open this model?

### ISSUE THREAD

**Issue by ludovicc** [canada-ca/NextGen-HR-Pay#1]
Hello,

Simple question: I tried to open the model in Archi (https://www.archimatetool.com/), but that doesn't work. Which tool do you use for modeling here?

**Comment by TroyMacFarlaneEA** [comment]
Hi, we are using Archi.  It may be easier if you add the github add-on that is available on the Archi site which will allow you to sync to github.  The model will appear as NextGen-HR-PAY in your list of available models.  I will try to create some setup screen shots once I have the cycles.  I've entered another sprint in our agile procurement process so I am very consumed with those activities.

**Comment by ludovicc** [comment]
Thanks, I was able to open the model. For reference, you need to install the 'Model Repository Collaboration Plugin' available from https://www.archimatetool.com/plugins/, then open this Github repository using menu Collaboration > Import remote model to workspace

**Comment by drobert55** [comment]
That worked for me me too.

Troy,  I have played around with Archimate in the past but mostly for process modeling.  Is there a good training/certification course you can recommend for someone to get fully up to speed on it?

Dan
613-863-6912
Linkedin.com/in/danrobert
